version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "3000:3000"
    environment:
      - PYTHONPATH=/app
      - PORT=3000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:3000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
